### ISSUE TITLE
Currently Watching

### ISSUE THREAD

**Issue by jbsix** [techygrrrl/multilang-twitch-tts#6]
Very cool app... however this might be user error but when I installed it and define "currently watching" it also plays anyone chatting on the twitch chat... how can I make the TTS only the one the app is "watching"?

**Comment by jbsix** [comment]
user error

**Comment by techygrrrl** [comment]
@jbsix no worries. The TTS app is designed to speak out all chat messages in a specific channel. There's the ability to add specific usernames to an [ignore list](https://blog.techygrrrl.stream/multilingual-tts-twitch#heading-ignore-list), e.g. your bots, but the opposite is not supported (i.e. watching only a specific user in the channel is not possible).

**Comment by jbsix** [comment]
thanks for responding! any thoughts or supporting the opposite concept? for example, if watching TTS otherwise ignore?

**Comment by techygrrrl** [comment]
@jbsix I don't see myself building this out but I'll add an issue to the board in case I change my mind: https://github.com/techygrrrl/multilang-twitch-tts/issues/7
