### ISSUE TITLE
[feature] Add ability to change sound output device

### ISSUE THREAD

**Issue by Masono03** [techygrrrl/multilang-twitch-tts#8]
hey i tried using windows sound management to change where the sound is coming from but it still always forcefully comes out of all playback devices :/ can we please get a on app setting to change audio output source since i cant use it if chat would hear it on stream i only want it to hear chat myself

**Comment by techygrrrl** [comment]
@Masono03 while this sounds like a great idea, I'm not sure how much control I have over routing audio to which device. By default, OBS detects all audio as "Desktop audio" unless you set up different audio channels yourself. I use the pre-installed StereoMix to route audio to different channels and only stream game audio and not TTS. As I've found other ways to do the exact thing you're requesting via Windows' native features, it's unlikely I'll be looking into how to solve this at the application-level.

I'm not sure what version of Windows you're on and which sound card and drivers you have, but on Windows with Realtek you can use a tool called StereoMix, which comes pre-installed on Windows and allows you to route audio. It's a bit confusing and cumbersome to use, but I use it for this exact purpose. 

Here are some instructions you can follow to set up different audio channels so you can share only game audio (and other audio) to OBS and not TTS: https://github.com/techygrrrl/multilang-twitch-tts/wiki/Audio-routing-and-changing-output-devices-for-TTS

Please give it a try and let me know if you think I can improve those docs. Thanks.

**Comment by Masono03** [comment]
Sadly i cant use stereomix since i am using voicemeeter potato for other splitting but also cant use the raw devices in streamlabs since potato does not allow other programs to acess the raw devices anymore :/ so im kinda on a stalemate since even if i select another of my voicemeeter outputs via sound setting it still comes out of the standard one as well :( idk why either so its very frustrating

**Comment by Masono03** [comment]
ok update i mightve found a way: if i go into ease of acess and set the output of the voice assistant to a basically dead line// unused virtual cable and then go into sound settings routing TTS itself to a used channel on my headset chat cant hear but i can it finally works! the "has started watching" at the start can be heard but not the TTS itself afterwards so this works for me :D

**Comment by techygrrrl** [comment]
> ok update i mightve found a way: if i go into ease of acess and set the output of the voice assistant to a basically dead line// unused virtual cable and then go into sound settings routing TTS itself to a used channel on my headset chat cant hear but i can it finally works! the "has started watching" at the start can be heard but not the TTS itself afterwards so this works for me :D

Really glad to hear you found a way to get it to work! I've linked back to this ticket in the wiki in case someone using this same software with the same issue needs some guidance. 

Closing this ticket since it's unlikely I'll be adding support for this since it works at the OS-level as well as with other audio mixing software.

**Comment by Masono03** [comment]
AH i have to reopen because as soon as i went live it stopped working again and is heard from all sources again
